# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_monitor.Host', verbose_name='主机'),
        ),
    ]
