# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0004_auto_20180102_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版本'),
        ),
    ]
