# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0005_auto_20180102_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namespaces',
            options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
    ]
