# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0006_auto_20180102_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespaces',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='项目名称'),
        ),
    ]
