# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0007_auto_20180102_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='username',
            field=models.CharField(default='root', max_length=64, verbose_name='系统用户'),
        ),
    ]
