# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0008_auto_20180106_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_active',
            field=models.IntegerField(blank=True, null=True, verbose_name='连接'),
        ),
    ]
