# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0009_auto_20180106_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_active',
            field=models.CharField(blank=True, default='未连接', max_length=12, null=True, verbose_name='连接'),
        ),
    ]
