# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0010_auto_20180106_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='cpu_total',
            field=models.CharField(max_length=12, verbose_name='CPU总数'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='cpu_use',
            field=models.CharField(max_length=12, verbose_name='CPU使用率'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='disk_total',
            field=models.CharField(max_length=12, verbose_name='磁盘总数'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='disk_use',
            field=models.CharField(max_length=12, verbose_name='磁盘使用率'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='host_input',
            field=models.CharField(max_length=12, verbose_name='下载流量'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='host_output',
            field=models.CharField(max_length=12, verbose_name='上传流量'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='ram_total',
            field=models.CharField(max_length=12, verbose_name='内存总数'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='ram_use',
            field=models.CharField(max_length=12, verbose_name='内存使用率'),
        ),
    ]
