# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0011_auto_20180110_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='pod_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='容器数量'),
        ),
    ]
