# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_monitor', '0015_auto_20180125_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='host_ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='对外IP'),
        ),
    ]
